services:
  scanservice:
    image: pietmacom/scanservice:latest
    build:
      context: .
      network: host
    privileged: true
    volumes:
#       - /mnt/pool1/shares/scan:/dest
       - /run/dbus:/host/run/dbus
       - /dev/bus/usb:/dev/bus/usb
    environment:
       UID: 3000
       GID: 3000

       
