services:
  scanservice:
    image: pietmacom/scanservice
    build:
      context: .
      network: host
    privileged: true
    volumes:
       - /dest:./scanned
       - /run/dbus:/host/run/dbus
       - /dev/bus/usb:/dev/bus/usb
    environment:
       UID: 3000
       GID: 3000

       
