#!/bin/bash -ex

## Environment from SCANBD
# SCANBD_ACTION=scan
# USER=nobody
# SCANBD_FUNCTION=3
# PWD=/
# HOME=/
# SCANBD_FUNCTION_MODE=Lineart
# SCANBD_DEVICE=fujitsu:fi-6110dj:1209721
# SHLVL=1
# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
# _=/usr/bin/printenv

destination="/dest"
workspace="$(mktemp -d ${destination}/scan.XXXXXXXXXX)"
worker=""
result=0

cd $workspace
/usr/bin/printenv > script.env

## SCANIMAGE
#
# Notes
# --swdeskew - Führt zu abgeschnittenen seiten
#
# BASE
SCANIMAGE="scanimage --device-name=\"$SCANBD_DEVICE\""

# +BACKEND
SCANIMAGE="${SCANIMAGE} --df-action=Stop --swskip=3 --buffermode=On --page-width=210 --page-height=297.1 -l 0 -t 0 --ald=yes"

# OPTIONS
SI_SOURCE_DUPLEX="--source=\"ADF Duplex\""
SI_SOURCE_FRONT="--source=\"ADF Front\""

SI_FORMAT_TIFF="--format=tiff --batch=./page_%04d.tiff"
SI_FORMAT_PNM="--format=pnm --batch=./page_%04d.pnm"

SI_MODE_COLOR="--mode=Color --emphasis=0 --contrast=35 --brightness=35"
SI_MODE_GRAY="--mode=Gray --emphasis=0 --contrast=20 --brightness=20"
SI_MODE_LINEART="--mode=Lineart --emphasis=0 --contrast=50 --brightness=0"
SI_MODE_HALFTIONE="--mode=Halftone --ht-type=Dither --ht-pattern=2"

echo "scanbd: $0 Begin of $SCANBD_ACTION for device $SCANBD_DEVICE"
case $SCANBD_ACTION in
	"scan")
		case $SCANBD_FUNCTION in
		    1)
				echo "Duplex, Lineart, PDF (OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_DUPLEX} \
				${SI_FORMAT_TIFF} \
				${SI_MODE_LINEART} \
				--resolution 300 \
				|| result=$?
				
				worker="tiffToPdf+ocr"
			;;
			
		    2)
				echo "Duplex, Halftone, PDF (OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_DUPLEX} \
				${SI_FORMAT_TIFF} \
				${SI_MODE_HALFTIONE} \
				--resolution 300 \
				|| result=$?
				
				worker="tiffToPdf+ocr"
			;;
	
		    3)
				echo "Duplex, Gray, PDF (no OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_DUPLEX} \
				${SI_FORMAT_PNM} \
				${SI_MODE_GRAY} \
				--resolution 300 \
				|| result=$?
				
				worker="pnmToPdf"
			;;
			
		    4)
				echo "Duplex, Color, PDF (no OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_DUPLEX} \
				${SI_FORMAT_TIFF} \
				${SI_MODE_COLOR} \
				--resolution 150 \
				|| result=$?
				
				worker="tiffToPdf+ocr"
			;;
	
		    5)
				echo "Front, Lineart, PDF (no OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_FRONT} \
				${SI_FORMAT_TIFF} \
				${SI_MODE_LINEART} \			
				--resolution 300 \
				|| result=$?
				
				worker="tiffToPdf+ocr"
			;;
	
		    6)
				echo "Front, Halftone, PDF (OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_FRONT} \
				${SI_FORMAT_TIFF} \
				${SI_MODE_HALFTONE} \	
				--resolution 300 \
				|| result=$?
				
				worker="tiffToPdf+ocr"
			;;
	
		    7)
				echo "Front, Gray, PDF (no OCR)"
	
				eval ${SCANIMAGE} \
				${SI_SOURCE_FRONT} \
				${SI_FORMAT_PNM} \
				${SI_MODE_GRAY} \
				--resolution 300 \
				|| result=$?
				
				worker="pnmToPdf"
			;;
			
		    8)
				echo "Front, Color, PDF (no OCR)"
				
				eval ${SCANIMAGE} \
				${SI_SOURCE_FRONT} \
				${SI_FORMAT_PNM} \
				${SI_MODE_COLOR} \
				--resolution 300 \
				|| result=$?
				
				worker="pnmToPdf"
			;;
	
		    9)
				echo "Front, Color, PDF (no OCR) trimmed"
		
				eval ${SCANIMAGE} \
				${SI_SOURCE_FRONT} \
				${SI_FORMAT_PNM} \
				${SI_MODE_COLOR} \
				--resolution 600 \
				|| result=$?
				
				worker="pnmToPdf+trim"
			;;
		esac
	;;

	"email")
		case $SCANBD_FUNCTION in
		esac
	;;
esac

if [ ! $result -eq 0 ];
then
    echo "Exit due failure"
    rm -rf $workspace
    exit
fi

tsp $(dirname $0)/my-worker.script $worker $workspace

echo "scanbd: $0 End   of $SCANBD_ACTION for device $SCANBD_DEVICE"
